/**
 * Account  Process
 * Account Process
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nombre.apellidos@gruposantander.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Error (
  /* Unique alphanumeric human readable error code */
  code: Option[String] = None,
  /* Brief summary of the reported issue */
  message: Option[String] = None,
  /* Level of the reported issue.    The possible values are   - info   - warning   - error */
  level: Option[String] = None,
  /* Detailed description of the reported issue */
  description: Option[String] = None
) extends ApiModel


